# Change these first
owner: solohost-webadmin # Your GitHub organization or username, where this repository lives
repo: solohost-status # The name of this repository

sites:
  - name: Site Landing
    url: https://www.solohost.dev/
  - name: Web Portal
    url: https://solohost.dev/yunohost/sso/
  - name: Main Status Page
    url: https://status.solohost.dev/
  - name: Hosting Server
    check: "tcp-ping"
    url: solohost.dev
    port: 443

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status-alt.solohost.dev
  favicon: https://www.solohost.dev/images/unk-net-new_ico3_var1_2.png
  # baseUrl: /your-repo-name
  logoUrl: https://www.solohost.dev/images/unk-net-new_ico3_var1_2.png
  name: Solohost Alt. Status
  introTitle: "**Welcome!**"
  introMessage: This is the alternative status page for solohost.dev! For more information. contact the [webmaster](https://contact.solohost.dev).
  theme: night
  navbar:
    - title: Site Landing
      href: https://www.solohost.dev/
    - title: Main Status Page
      href: https://status.solohost.dev/
    - title: Contact Webmaster
      href: https://contact.solohost.dev/
i18n:
  footer: "©️ solohost.dev | 2025 | [Page Source]($REPO), Powered by [Upptime](https://upptime.js.org/) | [Contact Webmaster](https://contact.solohost.dev/)"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
